### ISSUE TITLE
Spawning in walls when going to next floor

### ISSUE THREAD

**Issue by ShadowWolf426** [RexcellentGames/BurningKnight#14]
I wound up spawning in the wall on the daily run after beating the fist boss and going down the stairs to the temple floor.
![Wallscreenshot](https://user-images.githubusercontent.com/67282155/85308880-69f51a00-b477-11ea-93ae-b8b825716c92.png)

The seed for the daily run was LD1OG3UD that the bug occured.

**Comment by egordorichev** [comment]
Thanks so much for the seed, there was no way I'd find the issue without it :O This bug just been patched in `f89c638`.
For future me: the issue was an `ArrayOutOfBoundsException` in the `TileInteractionComponent` of player, the exception prevented future player code (including the one that is meant to teleport you to the entrance) from executing, and you'd basically be stuck in a loop.

Just wow, thanks again, this bug was hunting me for months!
